"""Optional speech, lip-sync, and character-render adapter planning.

Adapters turn a compiled scene into JSON-safe command plans for the optional
local tools: Piper synthesizes dialogue.text into a speech wav, Rhubarb turns
that wav into mouth-cue timings, and Blender renders the character plate
(delegated to `renderers.plan_blender_render`). All executable detection runs
through the shared `renderers.Toolchain`, so callers and tests inject lookups
and filter probes; a missing tool is plan status — `unavailable` with
`applied: false` and a named reason, mirroring the captions pattern — never a
raised error at import or detection time.
"""

from .renderers import (
    # Scene validation and asset-existence checks are renderers' planning
    # internals; adapters reuses them so every planner reports scenes alike.
    CAPTION_NOT_RENDERED_REASON,
    MissingToolError,
    Toolchain,
    _missing_assets,
    _require_scene,
    _scene_value,
    plan_blender_render as _renderers_plan_blender_render,
    resolve_relative_path,
)

ADAPTER_TOOLS = ("ffmpeg", "blender", "piper", "rhubarb")
PIPER_OUTPUT_NAME = "build/speech.wav"
RHUBARB_OUTPUT_NAME = "build/mouth-cues.json"
RHUBARB_LIP_SYNC = "rhubarb"
VOICE_MODEL_DIRECTORY = "assets/voices"
PIPER_UNAVAILABLE_REASON = (
    "piper executable not found; dialogue.text is kept in the plan so speech can "
    "be synthesized by a capable build or adapter"
)
RHUBARB_UNAVAILABLE_REASON = (
    "rhubarb executable not found; the speech wav is kept in the plan so mouth "
    "cues can be generated by a capable build or adapter"
)
BLENDER_UNAVAILABLE_REASON = (
    "blender executable not found; the character plate is not rendered and the "
    "scene keeps its baseline ffmpeg render path"
)


def adapter_status(toolchain=None):
    """Return a JSON-safe capability report for the optional adapter tools.

    Availability comes from the shared Toolchain lookup; the captions entry
    reports whether the installed ffmpeg can burn in captions with drawtext.
    """
    chain = _toolchain(toolchain)
    tools = {}
    for tool in ADAPTER_TOOLS:
        path = chain.resolve(tool)
        tools[tool] = {"available": bool(path), "path": path}
    applied = chain.supports_filter("ffmpeg", "drawtext")
    return {
        "tools": tools,
        "captions": {
            "applied": applied,
            "reason": None if applied else CAPTION_NOT_RENDERED_REASON,
        },
    }


def plan_piper_speech(
    scene,
    project_root,
    toolchain=None,
    *,
    output_name=PIPER_OUTPUT_NAME,
):
    """Plan local TTS: piper synthesizes dialogue.text into a speech wav.

    Piper reads its text from stdin, so the planned argv carries only the voice
    model and output flags and the text travels in the plan's `input` block for
    the execution layer. A scene voice names its piper model as
    `assets/voices/<voice>.onnx`, reported through `missing_assets` when the
    file is absent. A missing piper is the plan status `unavailable`; the text,
    voice, and wav path are kept so the scene stays usable.
    """
    _require_scene(scene)
    chain = _toolchain(toolchain)
    executable = chain.resolve("piper")
    dialogue = _scene_value(scene, "dialogue")
    text = _scene_value(dialogue, "text")
    voice = _scene_value(dialogue, "voice")
    model_path = resolve_relative_path(
        project_root, f"{VOICE_MODEL_DIRECTORY}/{voice}.onnx", "dialogue.voice_model"
    )
    output_path = resolve_relative_path(project_root, output_name, "output_name")
    applied = executable is not None
    argv = (
        [executable, "--model", model_path, "--output_file", output_path]
        if applied
        else None
    )
    return _finish_adapter_plan(
        "piper",
        executable,
        applied,
        None if applied else PIPER_UNAVAILABLE_REASON,
        argv,
        {"path": output_path, "format": "wav"},
        {"dialogue.voice_model": model_path},
        {"input": {"kind": "stdin", "text": text}, "voice": voice},
    )


def plan_rhubarb_lipsync(
    scene,
    project_root,
    toolchain=None,
    *,
    speech_path=PIPER_OUTPUT_NAME,
    output_name=RHUBARB_OUTPUT_NAME,
):
    """Plan lip sync: rhubarb derives mouth-cue timings from the speech wav.

    Rhubarb analyzes the wav and writes its `mouthCues` timings as JSON; the
    wav defaults to the piper plan's output so the two plans compose. The scene
    must request rhubarb in dialogue.lip_sync — anything else leaves the plan
    unapplied with a named reason. dialogue.text is kept as metadata because
    the accuracy-improving `--dialogFile` is a file planners never write. A
    missing rhubarb is the plan status `unavailable`; the wav and cue paths
    are kept so the scene stays usable.
    """
    _require_scene(scene)
    chain = _toolchain(toolchain)
    executable = chain.resolve("rhubarb")
    dialogue = _scene_value(scene, "dialogue")
    text = _scene_value(dialogue, "text")
    voice = _scene_value(dialogue, "voice")
    lip_sync = _scene_value(dialogue, "lip_sync")
    audio_path = resolve_relative_path(project_root, speech_path, "dialogue.audio")
    output_path = resolve_relative_path(project_root, output_name, "output_name")
    if lip_sync != RHUBARB_LIP_SYNC:
        applied = False
        reason = (
            f"dialogue.lip_sync is {lip_sync!r}; the rhubarb adapter plans mouth "
            f"cues only when the scene requests {RHUBARB_LIP_SYNC!r}"
        )
    elif executable is None:
        applied = False
        reason = RHUBARB_UNAVAILABLE_REASON
    else:
        applied = True
        reason = None
    argv = (
        [executable, "--exportFormat", "json", "--output", output_path, audio_path]
        if applied
        else None
    )
    return _finish_adapter_plan(
        "rhubarb",
        executable,
        applied,
        reason,
        argv,
        {"path": output_path, "format": "json"},
        {"dialogue.audio": audio_path},
        {"text": text, "voice": voice, "lip_sync": lip_sync},
    )


def plan_blender_render(scene, project_root, toolchain=None):
    """Plan the character plate render through `renderers.plan_blender_render`.

    Thin wrapper: when blender is available the renderers plan is returned
    unchanged plus `applied: true` and `reason: None`; a missing blender
    becomes the named plan status `unavailable` instead of a raised error, so
    the adapters surface reports every optional tool the same way.
    """
    try:
        plan = dict(
            _renderers_plan_blender_render(scene, project_root, _toolchain(toolchain))
        )
    except MissingToolError:
        return _finish_adapter_plan(
            "blender", None, False, BLENDER_UNAVAILABLE_REASON, None, None, {}, {}
        )
    plan["applied"] = True
    plan["reason"] = None
    return plan


def _toolchain(toolchain):
    return toolchain if toolchain is not None else Toolchain(tools=ADAPTER_TOOLS)


def _finish_adapter_plan(tool, executable, applied, reason, argv, output, assets, extra):
    missing = _missing_assets(assets)
    if executable is None:
        status = "unavailable"
    elif missing:
        status = "missing_assets"
    else:
        status = "ready"
    plan = {
        "tool": tool,
        "status": status,
        "applied": applied,
        "reason": reason,
        "executable": executable,
        "argv": [str(arg) for arg in argv] if argv is not None else None,
        "assets": dict(assets),
        "missing_assets": missing,
        "output": output,
    }
    plan.update(extra)
    return plan
